import { applyPublishedContent } from "../src/content.js";
import { setPlayerMatch, setPlayerSection, setPlayerTab } from "../src/player-view.js";

const ITEMS = ["裝備 1423", "裝備 1324", "裝備 1227", "裝備 1224", "裝備 1249", "裝備 1242"];

function row(partial) {
  return {
    side: "blue",
    hero: "娜塔亞",
    ign: "藍方",
    kills: "1",
    deaths: "1",
    assists: "1",
    gold: "8000",
    minions: "20",
    lastHits: "20",
    jungleGold: "400",
    healing: "1000",
    control: "500",
    tower: "800",
    heroDamage: "40000",
    taken: "30000",
    score: "8.0",
    items: ITEMS,
    owner: false,
    mvp: false,
    ...partial,
  };
}

/** Local-only overlay so the member shell can be screenshotted without live CMS data. */
export function applyPreview() {
  applyPublishedContent({
    rosterMembers: [
      {
        id: "owner0702",
        hidden: false,
        name: { zh: "htw0702aov", en: "htw0702aov" },
        role: { zh: "隊長", en: "Captain" },
      },
    ],
    player: {
      handle: "htw0702aov",
      publish: true,
      rank: { zh: "鉑金IV", en: "Platinum IV" },
      season: { zh: "2026-S4", en: "2026-S4" },
      heroPool: [
        { hero: "娜塔亞", matches: "60", winRate: "68.3", power: "2984" },
        { hero: "克里希", matches: "3", winRate: "100", power: "277" },
        { hero: "刀鋒寶貝", matches: "2", winRate: "50", power: "109" },
        { hero: "特爾安娜絲", matches: "2", winRate: "50", power: "206" },
      ],
      skins: [{ hero: "娜塔亞", name: "原皮" }],
      seasons: [
        {
          label: "2026-S4",
          mode: "排位賽",
          played: "9",
          wins: "6",
          winRate: "66.7",
          mvp: "4",
          radar: { output: "82", kda: "74", farm: "70", teamfight: "64", survival: "68" },
          medals: { triple: "2", silver: "3", gold: "0", godlike: "0", penta: "0", quadra: "0", supreme: "0", loseMvp: "0" },
        },
      ],
      matches: [
        {
          id: "m2259",
          publish: true,
          playedAt: "2026-09-25 22:59",
          duration: "15:17",
          mode: "排位賽",
          hero: "娜塔亞",
          result: "勝",
          kills: "8",
          deaths: "6",
          assists: "4",
          gold: "9819",
          damage: "125875",
          taken: "113770",
          minions: "34",
          lastHits: "34",
          jungleGold: "160",
          healing: "6077",
          control: "6.534",
          tower: "2089",
          damageRatio: "1.51",
          takenPer: "18961",
          rankDelta: "103",
          powerDelta: "63",
          mvp: true,
          blueScore: "25",
          redScore: "17",
          winner: "blue",
          ownerSide: "blue",
          board: [
            row({ hero: "弗洛倫", ign: "藍方甲", kills: "9", deaths: "4", assists: "3", gold: "11033", lastHits: "14", minions: "14", jungleGold: "2856", score: "9.6" }),
            row({ hero: "特爾安娜絲", ign: "藍方乙", kills: "3", deaths: "2", assists: "7", gold: "10982", lastHits: "38", minions: "38", score: "8.5" }),
            row({ hero: "塔拉", ign: "藍方丙", kills: "3", deaths: "2", assists: "5", gold: "10296", lastHits: "43", minions: "43", score: "7.6" }),
            row({ hero: "牛魔王", ign: "藍方丁", kills: "2", deaths: "3", assists: "14", gold: "9811", lastHits: "12", minions: "12", score: "8.4" }),
            row({
              hero: "娜塔亞",
              ign: "htw0702aov",
              owner: true,
              mvp: true,
              kills: "8",
              deaths: "6",
              assists: "4",
              gold: "9819",
              lastHits: "34",
              minions: "34",
              jungleGold: "160",
              healing: "6077",
              control: "6.534",
              tower: "2089",
              heroDamage: "125875",
              taken: "113770",
              damageRatio: "1.51",
              takenPer: "18961",
              teamfightRate: "48",
              score: "10.0",
              rankDelta: "103",
              powerDelta: "63",
            }),
            row({ side: "red", hero: "奎倫", ign: "紅方甲", kills: "7", deaths: "5", assists: "3", gold: "9811", score: "8.3" }),
            row({ side: "red", hero: "穆加爵", ign: "紅方乙", kills: "2", deaths: "6", assists: "5", gold: "9273", score: "5.9" }),
            row({ side: "red", hero: "納克羅斯", ign: "紅方丙", kills: "4", deaths: "5", assists: "4", gold: "9067", score: "6.7" }),
            row({ side: "red", hero: "安奈特", ign: "紅方丁", kills: "1", deaths: "3", assists: "15", gold: "9071", score: "10.7", mvp: true }),
            row({ side: "red", hero: "凱格路士", ign: "紅方戊", kills: "3", deaths: "6", assists: "2", gold: "10040", score: "7.1" }),
          ],
        },
        {
          id: "m1320",
          publish: true,
          playedAt: "2026-09-25 13:20",
          duration: "17:30",
          mode: "排位賽",
          hero: "娜塔亞",
          result: "敗",
          kills: "7",
          deaths: "10",
          assists: "5",
          gold: "9412",
          minions: "30",
          lastHits: "30",
          healing: "7964",
          tower: "2743",
          control: "8.382",
          rankDelta: "-99",
          mvp: false,
          blueScore: "20",
          redScore: "18",
          ownerSide: "red",
          board: [
            row({
              side: "red",
              hero: "娜塔亞",
              ign: "htw0702aov",
              owner: true,
              kills: "7",
              deaths: "10",
              assists: "5",
              gold: "9412",
              minions: "30",
              lastHits: "30",
              healing: "7964",
              tower: "2743",
              control: "8.382",
              score: "8.7",
            }),
          ],
        },
      ],
    },
  });
  const params = new URLSearchParams(window.location.search);
  if (params.get("section")) setPlayerSection(params.get("section"));
  if (params.get("match")) setPlayerMatch(params.get("match"));
  if (params.get("tab")) setPlayerTab(params.get("tab"));
}
