/**
 * Editable team facts.
 * Leave strings blank until they are confirmed. Do not invent championships,
 * player names, sponsors, match results, or a Discord invite.
 */

export const PLACEHOLDER_SLOTS = 5;

/** @type {{ id: string, name: { zh: string, en: string }, role: { zh: string, en: string } }[]} */
export const rosterMembers = [];

/** @type {{ id: string, date: string, title: { zh: string, en: string }, body: { zh: string, en: string } }[]} */
export const newsPosts = [];

export const profileFields = [
  { id: "founded", zh: "成立", en: "Founded", value: { zh: "", en: "" } },
  { id: "base", zh: "基地", en: "Base", value: { zh: "", en: "" } },
  { id: "season", zh: "目前賽季", en: "Season", value: { zh: "", en: "" } },
  { id: "record", zh: "戰績", en: "Record", value: { zh: "", en: "" } },
  { id: "sponsors", zh: "贊助", en: "Sponsors", value: { zh: "", en: "" } },
];

const zh = {
  meta: {
    homeTitle: "暮霞｜MOS — 傳說對決戰隊",
    homeDescription: "暮霞｜MOS，傳說對決戰隊。不開放招募。聯絡 Info@moohsia.com。",
    titleSuffix: "暮霞｜MOS",
  },
  nav: {
    home: "首頁",
    about: "戰隊",
    roster: "成員",
    news: "動態",
    contact: "聯絡",
    menu: "選單",
    close: "關閉",
    lang: "切換為 English",
    langShort: "EN",
    skip: "跳至內容",
    recruitChip: "不開放招募",
    sys: "CH // PUBLIC",
    footerLabel: "頁尾",
  },
  intro: {
    label: "暮霞｜MOS",
    sub: "ARENA OF VALOR",
    skip: "略過入場",
  },
  footer: {
    blurb: "傳說對決戰隊。",
    rule: "不開放招募。",
    recruit: "不開放招募",
    explore: "站內",
  },
  home: {
    kicker: "ARENA OF VALOR",
    kickerZh: "傳說對決戰隊",
    tagline: "暮色未歇，戰線仍在。",
    taglineAlt: "Dusk holds. The line stays.",
    lead: "暮霞｜MOS，傳說對決戰隊。暮色未歇，戰線仍在。目前不開放招募。",
    ctaTeam: "進入戰隊",
    ctaRoster: "成員席位",
    ctaContact: "聯絡信箱",
    chips: [
      { text: "傳說對決", tone: "calm" },
      { text: "不開放招募", tone: "alert" },
      { text: "戰績尚未公布", tone: "calm" },
      { text: "成員資訊即將公開", tone: "calm" },
    ],
    crestSig: "SIG // DUSK",
    crestRec: "GATE // CLOSED",
    hudChannel: "CH // PUBLIC",
    hudGame: "AOV // 傳說對決",
    ticker: "暮霞｜MOS · 傳說對決 · 不開放招募 · 成員資訊即將公開 · Info@moohsia.com · 戰績尚未公布 · ",
    metricsKicker: "00 — STAGE",
    metrics: [
      { index: "01", label: "主場", value: "傳說對決", note: "Arena of Valor" },
      { index: "02", label: "招募", value: "不開放招募", note: "目前沒有試訓" },
      { index: "03", label: "名單", value: "即將公開", note: "成員資訊即將公開" },
      { index: "04", label: "信箱", value: "戰隊信箱", note: "Info@moohsia.com" },
    ],
    identityKicker: "01 — IDENTITY",
    identityTitle: "關於暮霞",
    identityLead: "以暮色為名，站上傳說對決。",
    cards: [
      {
        index: "01",
        title: "戰隊",
        body: "暮霞｜MOS（MOS / Moohsia），傳說對決戰隊。",
      },
      {
        index: "02",
        title: "暮色",
        body: "餘燼、堇紫與暮色，是這支隊伍的顏色。",
      },
      {
        index: "03",
        title: "招募",
        body: "不開放招募。目前沒有試訓。",
      },
      {
        index: "04",
        title: "戰績",
        body: "賽季戰績尚未公布。",
      },
    ],
    boardKicker: "02 — STATUS",
    boardTitle: "現況",
    boardNote: "",
    rows: [
      ["遊戲", "傳說對決"],
      ["公開招募", "不開放招募"],
      ["試訓申請", "不受理"],
      ["成員名單", "成員資訊即將公開"],
      ["賽事成績", "尚未公布"],
      ["贊助", "尚未公開"],
      ["聯絡", "Info@moohsia.com"],
    ],
    fixtureKicker: "03 — FIXTURE",
    fixtureTitle: "下一場",
    fixtureLead: "賽程尚未公布。",
    fixtureNote: "",
    fixtures: [
      { id: "NEXT", title: "尚未公布", meta: "對手與時間待定" },
    ],
    rosterKicker: "04 — ROSTER",
    rosterTitle: "成員",
    rosterLead: "名單即將公布。",
    rosterCta: "查看成員",
    signalKicker: "05 — SIGNAL",
    signalTitle: "戰隊動態",
    signalCta: "開啟動態台",
    finaleKicker: "06 — TRANSMIT",
    finaleTitle: "聯絡戰隊",
    finaleBody: "媒體、合作與戰隊事務，請寄到這個信箱。目前不開放招募。",
  },
  about: {
    kicker: "02 — TEAM",
    title: "戰隊",
    lead: "暮霞｜MOS 是傳說對決戰隊。暮色未歇，戰線仍在。",
    pending: "待公布",
    manifestoKicker: "DUSK",
    manifestoTitle: "暮色未歇",
    manifesto: "名字取自暮色將盡、餘燼仍亮的時刻。我們站在傳說對決的戰場上。",
    principlesKicker: "NOW",
    principlesTitle: "此刻",
    principles: [
      "主場是傳說對決。",
      "不開放招募。",
      "成員資訊即將公開。",
      "賽季戰績尚未公布。",
      "贊助尚未公布。",
      "聯絡 Info@moohsia.com。",
    ],
    recruitTitle: "不開放招募",
    recruitBody: "目前沒有試訓。",
  },
  roster: {
    kicker: "03 — ROSTER",
    title: "成員",
    lead: "成員資訊即將公開。",
    slot: "成員資訊即將公開",
    slotMeta: "位置尚未公布",
    stamp: "待公布",
    stampLive: "已公開",
    emptyNote: "名單即將公布。",
    liveLead: "上場名單。",
    rolePending: "位置未公開",
    stageKicker: "LINEUP // PENDING",
  },
  news: {
    kicker: "04 — SIGNAL",
    title: "動態",
    lead: "賽事與戰隊消息。",
    emptyTitle: "目前沒有新消息",
    emptyBody: "新的公告會出現在這裡。",
    silent: "SIGNAL // SILENT",
    feed: "NO PUBLIC FEED",
    wireLabel: "訊息",
    reserved: [
      { id: "01", title: "尚無公告", meta: "—" },
      { id: "02", title: "尚無賽事", meta: "—" },
      { id: "03", title: "尚無戰績", meta: "—" },
    ],
    reservedNote: "",
  },
  contact: {
    kicker: "05 — CONTACT",
    title: "聯絡",
    lead: "媒體、合作與戰隊事務，寫信到這裡。",
    emailLabel: "寫信給戰隊",
    only: "Info@moohsia.com",
    recruitTitle: "不開放招募",
    recruitBody: "目前沒有試訓。",
    sheetKicker: "CHANNELS",
    sheet: [
      ["01  信箱", "Info@moohsia.com", "開放"],
      ["02  招募", "不開放招募", "關閉"],
      ["03  試訓", "目前沒有", "關閉"],
    ],
    writeTitle: "戰隊信箱",
    writeBody: "請寄到 Info@moohsia.com。目前不開放招募。",
  },
  notFound: {
    kicker: "404 — OFF MAP",
    title: "找不到這個頁面",
    lead: "這個網址不在戰隊站內。",
    back: "回到首頁",
  },
};

const en = {
  meta: {
    homeTitle: "MOS — Arena of Valor team",
    homeDescription: "暮霞｜MOS is an Arena of Valor team. Recruitment is closed. Contact Info@moohsia.com.",
    titleSuffix: "暮霞｜MOS",
  },
  nav: {
    home: "Home",
    about: "Team",
    roster: "Roster",
    news: "News",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
    lang: "切換為繁體中文",
    langShort: "中",
    skip: "Skip to content",
    recruitChip: "Recruitment closed",
    sys: "CH // PUBLIC",
    footerLabel: "Footer",
  },
  intro: {
    label: "暮霞｜MOS",
    sub: "ARENA OF VALOR",
    skip: "Skip intro",
  },
  footer: {
    blurb: "Arena of Valor team.",
    rule: "Recruitment is closed.",
    recruit: "Recruitment closed",
    explore: "On this site",
  },
  home: {
    kicker: "ARENA OF VALOR",
    kickerZh: "暮霞｜MOS",
    tagline: "Dusk holds. The line stays.",
    taglineAlt: "暮色未歇，戰線仍在。",
    lead: "暮霞｜MOS is an Arena of Valor team. Dusk holds. The line stays. Recruitment is closed.",
    ctaTeam: "Enter the team",
    ctaRoster: "Roster",
    ctaContact: "Email",
    chips: [
      { text: "Arena of Valor", tone: "calm" },
      { text: "Recruitment closed", tone: "alert" },
      { text: "Record unannounced", tone: "calm" },
      { text: "Roster pending", tone: "calm" },
    ],
    crestSig: "SIG // DUSK",
    crestRec: "GATE // CLOSED",
    hudChannel: "CH // PUBLIC",
    hudGame: "AOV // ARENA OF VALOR",
    ticker: "暮霞｜MOS · ARENA OF VALOR · RECRUITMENT CLOSED · ROSTER PENDING · Info@moohsia.com · RECORD UNANNOUNCED · ",
    metricsKicker: "00 — STAGE",
    metrics: [
      { index: "01", label: "Title", value: "Arena of Valor", note: "Home game" },
      { index: "02", label: "Gate", value: "Closed", note: "No tryouts" },
      { index: "03", label: "Lineup", value: "Soon", note: "Roster coming soon" },
      { index: "04", label: "Mail", value: "Team inbox", note: "Info@moohsia.com" },
    ],
    identityKicker: "01 — IDENTITY",
    identityTitle: "About MOS",
    identityLead: "Named for dusk. Playing Arena of Valor.",
    cards: [
      {
        index: "01",
        title: "The team",
        body: "暮霞｜MOS (MOS / Moohsia) is an Arena of Valor team.",
      },
      {
        index: "02",
        title: "Dusk",
        body: "Ember, violet, and dusk are the colors of this team.",
      },
      {
        index: "03",
        title: "Recruitment",
        body: "Recruitment is closed. There are no tryouts.",
      },
      {
        index: "04",
        title: "Record",
        body: "This season’s results are not out yet.",
      },
    ],
    boardKicker: "02 — STATUS",
    boardTitle: "Right now",
    boardNote: "",
    rows: [
      ["Title", "Arena of Valor"],
      ["Recruitment", "Closed"],
      ["Tryouts", "Not accepted"],
      ["Roster", "Coming soon"],
      ["Match record", "Not published"],
      ["Sponsors", "Not published"],
      ["Contact", "Info@moohsia.com"],
    ],
    fixtureKicker: "03 — FIXTURE",
    fixtureTitle: "Next match",
    fixtureLead: "The schedule is not out yet.",
    fixtureNote: "",
    fixtures: [
      { id: "NEXT", title: "To be announced", meta: "Opponent and time TBA" },
    ],
    rosterKicker: "04 — ROSTER",
    rosterTitle: "Roster",
    rosterLead: "The lineup is coming soon.",
    rosterCta: "View roster",
    signalKicker: "05 — SIGNAL",
    signalTitle: "Team signal",
    signalCta: "Open the feed",
    finaleKicker: "06 — TRANSMIT",
    finaleTitle: "Reach the team",
    finaleBody: "Press, partners, and team business: write to this address. Recruitment is closed.",
  },
  about: {
    kicker: "02 — TEAM",
    title: "Team",
    lead: "暮霞｜MOS is an Arena of Valor team. Dusk holds. The line stays.",
    pending: "To be announced",
    manifestoKicker: "DUSK",
    manifestoTitle: "Dusk holds",
    manifesto: "The name is the last light of dusk, while the embers are still bright. This team plays Arena of Valor.",
    principlesKicker: "NOW",
    principlesTitle: "Right now",
    principles: [
      "The game is Arena of Valor.",
      "Recruitment is closed.",
      "The roster is coming soon.",
      "This season’s results are not out yet.",
      "Sponsors are not announced.",
      "Contact Info@moohsia.com.",
    ],
    recruitTitle: "Recruitment is closed",
    recruitBody: "There are no tryouts.",
  },
  roster: {
    kicker: "03 — ROSTER",
    title: "Roster",
    lead: "The roster is coming soon.",
    slot: "Roster coming soon",
    slotMeta: "Role to be announced",
    stamp: "Pending",
    stampLive: "Active",
    emptyNote: "Lineup coming soon.",
    liveLead: "The lineup.",
    rolePending: "Role unannounced",
    stageKicker: "LINEUP // PENDING",
  },
  news: {
    kicker: "04 — SIGNAL",
    title: "News",
    lead: "Matches and team news.",
    emptyTitle: "No news yet",
    emptyBody: "New posts will show up here.",
    silent: "SIGNAL // SILENT",
    feed: "NO PUBLIC FEED",
    wireLabel: "Wire",
    reserved: [
      { id: "01", title: "No announcement", meta: "—" },
      { id: "02", title: "No fixture", meta: "—" },
      { id: "03", title: "No result", meta: "—" },
    ],
    reservedNote: "",
  },
  contact: {
    kicker: "05 — CONTACT",
    title: "Contact",
    lead: "Press, partners, and team business: write here.",
    emailLabel: "Email the team",
    only: "Info@moohsia.com",
    recruitTitle: "Recruitment is closed",
    recruitBody: "There are no tryouts.",
    sheetKicker: "CHANNELS",
    sheet: [
      ["01  Mail", "Info@moohsia.com", "Open"],
      ["02  Recruit", "Closed", "Shut"],
      ["03  Tryouts", "None", "Shut"],
    ],
    writeTitle: "Team inbox",
    writeBody: "Write to Info@moohsia.com. Recruitment is closed.",
  },
  notFound: {
    kicker: "404 — OFF MAP",
    title: "Page not on the map",
    lead: "That address is not part of the team site.",
    back: "Back home",
  },
};

export function getCopy(lang) {
  return lang === "en" ? en : zh;
}

export const NAV = [
  { href: "/", key: "home" },
  { href: "/about", key: "about" },
  { href: "/roster", key: "roster" },
  { href: "/news", key: "news" },
  { href: "/contact", key: "contact" },
];
