import { CONTACT_EMAIL } from "../shared/brand.js";
import { cleanPlayer, emptyPlayer, toPublicPlayer } from "../shared/player.js";
import { memberTeamSlug } from "../shared/teams.js";

/**
 * Editable team facts.
 * Leave strings blank until they are confirmed. Do not invent championships,
 * player names, sponsors, match results, or a Discord invite.
 *
 * These values are the built-in defaults. The public site replaces them with
 * the published CMS document when one exists.
 */

export const PLACEHOLDER_SLOTS = 5;

/** @type {{ id: string, name: { zh: string, en: string }, role: { zh: string, en: string }, team?: string }[]} */
export const rosterMembers = [];

/** Competitive teams under the guild. Add another object to open `/teams/:slug`. */
export const teams = [
  {
    id: "moohsia",
    slug: "moohsia",
    name: { zh: "MOOHSIA", en: "MOOHSIA" },
    aka: { zh: "暮霞", en: "Dusk" },
    lead: {
      zh: "公會暮霞｜MOS 底下的戰隊。加入公會請走官網申請。",
      en: "A competitive team in the 暮霞｜MOS guild. Apply on this site to join the guild.",
    },
    requirements: [
      { zh: "每個週末 20:30–21:30 訓練", en: "Weekend training, 20:30–21:30." },
      { zh: "每個人至少擅長 2 路，且各路至少 5 隻熟悉英雄", en: "At least two lanes, with at least five familiar heroes in each." },
      { zh: "排位至少黃金以上", en: "Ranked Gold or above." },
    ],
  },
];

/** @type {{ id: string, date: string, title: { zh: string, en: string }, body: { zh: string, en: string } }[]} */
export const newsPosts = [];

export const profileFields = [
  { id: "founded", zh: "成立", en: "Founded", value: { zh: "", en: "" } },
  { id: "base", zh: "基地", en: "Base", value: { zh: "", en: "" } },
  { id: "season", zh: "目前賽季", en: "Season", value: { zh: "", en: "" } },
  { id: "record", zh: "戰績", en: "Record", value: { zh: "", en: "" } },
  { id: "sponsors", zh: "贊助", en: "Sponsors", value: { zh: "", en: "" } },
];

const zh = {
  meta: {
    homeTitle: "暮霞｜MOS — 傳說對決公會",
    homeDescription: "公會暮霞｜MOS（MOOHSIA）。加入只接受官網申請。聯絡 Info@moohsia.com。",
    titleSuffix: "暮霞｜MOS",
  },
  nav: {
    home: "首頁",
    about: "公會",
    teams: "戰隊",
    roster: "成員",
    heroSkills: "英雄技能",
    userSkills: "使用者技能",
    ultimates: "奧義",
    news: "動態",
    contact: "聯絡",
    player: "選手",
    heroes: "英雄",
    skins: "造型",
    items: "裝備",
    modes: "模式",
    activities: "活動",
    apply: "申請",
    menu: "選單",
    close: "關閉",
    lang: "切換為 English",
    langShort: "EN",
    skip: "跳至內容",
    recruitChip: "官網申請",
    sys: "CH // PUBLIC",
    footerLabel: "頁尾",
  },
  search: {
    label: "搜尋",
    placeholder: "英雄、技能、奧義、裝備",
    empty: "沒有符合的結果",
    hero: "英雄",
    skin: "造型",
    item: "裝備",
    skill: "英雄技能",
    userSkill: "使用者技能",
    arcana: "奧義",
    page: "頁面",
  },
  intro: {
    label: "暮霞｜MOS",
    sub: "ARENA OF VALOR",
    skip: "略過入場",
  },
  footer: {
    blurb: "公會暮霞｜MOS（MOOHSIA）。",
    rule: "加入只接受官網申請。Discord 不開放加入。",
    recruit: "官網申請",
    explore: "站內",
  },
  home: {
    kicker: "ARENA OF VALOR",
    kickerZh: "傳說對決公會",
    tagline: "暮色未歇，戰線仍在。",
    taglineAlt: "Dusk holds. The line stays.",
    lead: "公會暮霞｜MOS（MOOHSIA）。暮色未歇，戰線仍在。加入只走官網申請，Discord 不開放加入。",
    ctaTeam: "進入公會",
    ctaRoster: "成員席位",
    ctaContact: "聯絡信箱",
    ctaApply: "提出申請",
    chips: [
      { text: "傳說對決", tone: "calm" },
      { text: "官網申請", tone: "alert" },
      { text: "戰績尚未公布", tone: "calm" },
      { text: "成員資訊即將公開", tone: "calm" },
    ],
    crestSig: "SIG // DUSK",
    crestRec: "APPLY // SITE",
    hudChannel: "CH // PUBLIC",
    hudGame: "AOV // 傳說對決",
    ticker: "公會暮霞｜MOS · MOOHSIA · 傳說對決 · 官網申請 · Discord 不開放加入 · 成員資訊即將公開 · Info@moohsia.com · ",
    metricsKicker: "00 — STAGE",
    metrics: [
      { index: "01", label: "主場", value: "傳說對決", note: "Arena of Valor" },
      { index: "02", label: "招募", value: "官網申請", note: "Discord 不開放加入" },
      { index: "03", label: "名單", value: "即將公開", note: "成員資訊即將公開" },
      { index: "04", label: "信箱", value: "公會信箱", note: "Info@moohsia.com" },
    ],
    identityKicker: "01 — IDENTITY",
    identityTitle: "關於暮霞",
    identityLead: "以暮色為名，站上傳說對決。",
    cards: [
      {
        index: "01",
        title: "公會",
        body: "公會暮霞｜MOS（MOOHSIA），傳說對決。底下的戰隊另列。",
      },
      {
        index: "02",
        title: "暮色",
        body: "餘燼、堇紫與暮色，是這支公會的顏色。",
      },
      {
        index: "03",
        title: "招募",
        body: "加入只接受官方網站申請。Discord 不開放加入。",
      },
      {
        index: "04",
        title: "戰績",
        body: "賽季戰績尚未公布。",
      },
    ],
    boardKicker: "02 — STATUS",
    boardTitle: "現況",
    boardNote: "",
    rows: [
      ["遊戲", "傳說對決"],
      ["公開招募", "官網申請"],
      ["Discord", "不開放加入"],
      ["成員名單", "成員資訊即將公開"],
      ["賽事成績", "尚未公布"],
      ["贊助", "尚未公開"],
      ["聯絡", "Info@moohsia.com"],
    ],
    fixtureKicker: "03 — FIXTURE",
    fixtureTitle: "下一場",
    fixtureLead: "賽程尚未公布。",
    fixtureNote: "",
    fixtures: [
      { id: "NEXT", title: "尚未公布", meta: "對手與時間待定" },
    ],
    rosterKicker: "04 — ROSTER",
    rosterTitle: "成員",
    rosterLead: "名單即將公布。",
    rosterCta: "查看成員",
    signalKicker: "05 — SIGNAL",
    signalTitle: "公會動態",
    signalCta: "開啟動態台",
    finaleKicker: "06 — TRANSMIT",
    finaleTitle: "聯絡公會",
    finaleBody: "媒體、合作與公會事務，請寄到這個信箱。加入請用官網申請。",
    playerKicker: "07 — PLAYER",
    playerTitle: "選手數據",
    playerLead: "只顯示已經公開的個人資料。",
    playerCta: "查看玩家資料",
    playerEmpty: "個人數據尚未公布。",
    catalogKicker: "08 — CATALOG",
    catalogTitle: "英雄與模式",
    catalogLead: "官方公開名單。不是公會戰績。",
    heroesCta: "英雄名單",
    modesCta: "遊戲模式",
  },
  about: {
    kicker: "02 — GUILD",
    title: "公會",
    lead: "公會暮霞｜MOS（MOOHSIA）。暮色未歇，戰線仍在。",
    pending: "待公布",
    manifestoKicker: "DUSK",
    manifestoTitle: "暮色未歇",
    manifesto: "名字取自暮色將盡、餘燼仍亮的時刻。我們站在傳說對決的戰場上。",
    principlesKicker: "NOW",
    principlesTitle: "此刻",
    principles: [
      "主場是傳說對決。",
      "加入只接受官網申請。Discord 不開放加入。",
      "成員資訊即將公開。",
      "賽季戰績尚未公布。",
      "贊助尚未公布。",
      "聯絡 Info@moohsia.com。",
    ],
    recruitTitle: "官網申請",
    recruitBody: "想加入請填官方網站的申請。Discord 不開放加入，邀請由擁有者在核准後個別寄出。",
  },
  roster: {
    kicker: "03 — ROSTER",
    title: "成員",
    lead: "成員資訊即將公開。",
    slot: "成員資訊即將公開",
    slotMeta: "位置尚未公布",
    stamp: "待公布",
    stampLive: "已公開",
    emptyNote: "名單即將公布。",
    liveLead: "上場名單。",
    rolePending: "位置未公開",
    stageKicker: "LINEUP // PENDING",
    columns: { name: "成員", role: "位置", team: "戰隊" },
  },
  teams: {
    kicker: "03 — TEAMS",
    title: "戰隊名單",
    lead: "公會暮霞｜MOS 底下的戰隊。",
    emptyTitle: "目前沒有公開戰隊",
    emptyBody: "戰隊公布之後會列在這裡。",
    open: "查看戰隊",
    aka: "又稱",
    requirements: "加入條件",
    members: "成員",
    membersEmpty: "這支戰隊還沒有公開成員。",
    apply: "提出申請",
    applyNote: "加入公會請走官網申請。戰隊條件列在下面，通過後由擁有者安排。",
    missing: "找不到這支戰隊。",
  },
  skills: {
    kicker: "08 — SKILLS",
    title: "英雄技能",
    lead: "全部英雄的被動與技能，整理自 Garena 公開英雄頁。這是英雄技能，不是奧義。",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    noMatch: "這個條件下沒有英雄技能。",
    source: "資料來源：Garena 傳說對決官方英雄頁。",
    method: "四個技能的頁面依序是被動、一技能、二技能、三技能。說明裡的 {0} 是官方頁的數值占位，本站不另填冷卻或傷害。",
    unresolved: "這些英雄的技能數不是 4，依公開頁順序標示，不猜測哪一個是被動：",
    search: "搜尋英雄或技能",
    all: "全部",
    count: "位英雄",
  },
  userSkills: {
    kicker: "09 — USER",
    title: "使用者技能",
    lead: "對局裡玩家自己帶的技能，例如瞬移。不是英雄技能。Garena 公開頁稱作挑戰者技能。",
    official: "挑戰者技能",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    source: "資料來源：Garena 傳說對決公開頁。",
    count: "個技能",
  },
  ultimates: {
    kicker: "10 — ARCANA",
    title: "奧義",
    lead: "戰前配裝的魔紋。Garena 公開頁稱作奧義列表，分成一級到三級。不是英雄的第四個技能。",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    noMatch: "這個條件下沒有奧義。",
    source: "資料來源：Garena 傳說對決公開奧義列表。",
    method: "名稱、等級、屬性與效果都來自公開奧義列表。本站不改數值。",
    search: "搜尋奧義",
    levelAll: "全部等級",
    tagAll: "全部屬性",
    levels: { 1: "一級", 2: "二級", 3: "三級" },
    count: "個奧義",
    listLink: "奧義列表",
    glyphsTitle: "魔紋屬系",
    glyphsLead: "Garena 另公告過一套魔紋系統，和這份奧義列表是兩套配裝。公開的遊戲頁目前沒有逐條魔紋與數值，所以下面只列四個屬系。",
    glyphsPendingStamp: "待公布",
    glyphsPending: "官方公開頁尚未列出這一系的逐條魔紋與數值。",
    glyphsSource: "魔紋系統公告",
  },
  news: {
    kicker: "04 — SIGNAL",
    title: "動態",
    lead: "賽事與公會消息。",
    emptyTitle: "目前沒有新消息",
    emptyBody: "新的公告會出現在這裡。",
    silent: "SIGNAL // SILENT",
    feed: "NO PUBLIC FEED",
    wireLabel: "訊息",
    reserved: [
      { id: "01", title: "尚無公告", meta: "—" },
      { id: "02", title: "尚無賽事", meta: "—" },
      { id: "03", title: "尚無戰績", meta: "—" },
    ],
    reservedNote: "",
  },
  contact: {
    kicker: "05 — CONTACT",
    title: "聯絡",
    lead: "媒體、合作與公會事務，寫信到這裡。",
    emailLabel: "寫信給公會",
    only: "Info@moohsia.com",
    recruitTitle: "官網申請",
    recruitBody: "加入只接受這個網站的申請。Discord 不開放加入。",
    sheetKicker: "CHANNELS",
    sheet: [
      ["01  信箱", "Info@moohsia.com", "開放"],
      ["02  招募", "官網申請", "開放"],
      ["03  Discord", "不開放加入", "關閉"],
    ],
    writeTitle: "公會信箱",
    writeBody: "請寄到 Info@moohsia.com。加入請用官網申請。",
  },
  notFound: {
    kicker: "404 — OFF MAP",
    title: "找不到這個頁面",
    lead: "這個網址不在公會站內。",
    back: "回到首頁",
  },
  player: {
    kicker: "07 — PLAYER",
    title: "玩家資料",
    lead: "個人戰績只顯示已公開的資料。",
    emptyTitle: "尚未公布",
    emptyBody: "個人數據還沒有公開。填上並發布之後，才會出現在這裡。",
    pending: "待公布",
    handleLabel: "遊戲 ID",
    nameLabel: "顯示名稱",
    roleLabel: "位置",
    laneLabel: "路線",
    rankLabel: "段位",
    peakLabel: "歷史最高",
    joinLabel: "加入",
    seasonLabel: "賽季",
    serverLabel: "伺服器",
    titleLabel: "頭銜",
    heroesLabel: "常用英雄",
    bioLabel: "簡介",
    statsKicker: "RECORD",
    matchesKicker: "MATCHES",
    matchesEmpty: "沒有已公開的對局。",
    played: "場次",
    wins: "勝場",
    winRate: "勝率",
    kda: "KDA",
    kills: "擊殺",
    deaths: "死亡",
    assists: "助攻",
    gold: "經濟",
    damage: "輸出",
    mvp: "MVP",
    minions: "補刀數",
    lastHits: "補刀數",
    jungle: "野怪經濟",
    goldTotal: "總經濟",
    healing: "治療量",
    tower: "對塔傷害",
    control: "控制效果",
    damageRatio: "傷害轉化比",
    takenPer: "每次承傷",
    takenLabel: "承受傷害",
    heroDamage: "對英雄傷害",
    teamfight: "參團率",
    rankDelta: "積分",
    power: "傳說戰力",
    score: "評分",
    uidLabel: "UID",
    sections: {
      heroes: "常用英雄",
      history: "歷史戰績",
      analysis: "分析",
      battle: "對戰資料",
      builds: "配裝",
      reputation: "信譽積分",
      honors: "冠軍賽榮譽",
      titles: "榮譽頭銜",
      bonds: "親密關係",
    },
    radar: { output: "輸出", kda: "KDA", farm: "發育", teamfight: "團戰", survival: "生存" },
    medals: {
      godlike: "超神",
      penta: "五殺",
      quadra: "四殺",
      triple: "三殺",
      supreme: "頂級",
      gold: "金牌",
      silver: "銀牌",
      loseMvp: "敗方MVP",
    },
    tabs: {
      board: "總覽",
      data: "數據",
      output: "輸出",
      survival: "生存",
      farm: "發育",
      record: "戰績",
      team: "團隊",
    },
    charts: "圖表",
    analysis: {
      title: "分析",
      lead: "只從已公開的對局計算。",
      empty: "資料不足",
      recent: "近況勝率",
      last10: "近 10 場",
      last20: "近 20 場",
      overall: "全部",
      record: "{wins}勝{losses}敗",
      games: "{n} 場",
      heroes: "常用英雄勝率",
      trend: "KDA／輸出趨勢",
      trendNote: "由左到右是較早到較近的對局。",
      when: "時間",
      kda: "KDA",
      damage: "輸出",
      compare: "勝敗對比",
      winWord: "勝",
      lossWord: "敗",
      gold: "經濟",
      average: "平均",
      modes: "模式分布",
      modesNote: "依對局的模式，有地圖時一併標出。",
      myriad: "萬",
    },
    highlight: "精彩對局",
    noChart: "這項還沒有可畫的數字。",
    reputationEmpty: "信譽積分尚未填寫。",
    honorsEmpty: "冠軍賽榮譽尚未公布。",
    titlesEmpty: "榮譽頭銜尚未公布。",
    heroesEmpty: "常用英雄尚未公布。",
    buildsEmpty: "還沒有可以整理的出裝。",
    buildsTitle: "常用出裝",
    skinsTitle: "造型",
    skinsEmpty: "目前沒有造型紀錄。",
    heroTable: "英雄詳細資料",
    classic: "經典模式",
    magic: "魔法棋",
    magicEmpty: "目前沒有任何對戰記錄",
    bondsEmpty: "目前沒有親密關係資料。",
    derivedNote: "場次與勝率依已公開對局計算。雷達與勳章要等賽季資料填上。",
    columns: { hero: "英雄", result: "結果", points: "積分", items: "裝備", mode: "模式" },
    openDetail: "展開對局",
    skillOrder: "升級順序",
    items: "裝備",
    boots: "鞋子",
    enchant: "附魔",
    arcana: "奧義",
    skin: "造型",
    map: "地圖",
  },
  activities: {
    kicker: "10 — OFFICIAL",
    title: "官方活動",
    lead: "Garena 公開頁上的活動、公告與賽事。不是公會自己的賽程。",
    emptyTitle: "目前沒有抓到活動",
    emptyBody: "每日更新或管理頁的重新整理之後，公開列表會出現在這裡。",
    source: "來源是 Garena 傳說對決公開新聞頁。是否仍在進行，以官方頁為準。",
    all: "全部",
    activity: "活動",
    announcement: "公告",
    esports: "賽事",
    open: "官方原文",
  },
  apply: {
    kicker: "11 — APPLY",
    title: "加入申請",
    lead: "公會暮霞｜MOS（MOOHSIA）只接受這個網站的申請。Discord 不開放加入。",
    teamNote: "這是公會申請。各戰隊的加入條件在戰隊頁，MOOHSIA 的條件也寫在那一頁。",
    rank: "歷史排位賽最高戰績",
    rankHint: "最低黃金。低於黃金的申請不會送出。",
    uid: "使用者 UID",
    uidHint: "全數字。",
    nickname: "暱稱",
    email: "聯絡信箱",
    gender: "性別",
    age: "年齡層",
    motivation: "為什麼希望加入",
    positions: "適合的位子",
    positionsHint: "請剛好選 2 個。",
    weekday: "平日遊玩時間",
    holiday: "假日遊玩時間",
    practice: "可配合練習的時間",
    practiceHint: "請寫具體時段，例如 20:00～22:00。",
    conduct: "我了解並同意：尊重、友善、包容；禁止金錢往來；一切跟隨官方規範。",
    submit: "送出申請",
    discord: "Discord 不開放公開加入。通過之後，擁有者會用電子郵件寄出一次性邀請。",
    sent: "申請已收到。",
    sentBody: "若信件有設定，擁有者會在 Info@moohsia.com 看到這筆申請。",
    mailDelayed: "申請已留下。通知信可能會晚一點才寄出，這筆申請仍然算數。",
    fail: "這次沒有送出。",
    errors: {
      rank_below_gold: "歷史最高戰績要在黃金以上。",
      uid_invalid: "UID 要是 4 到 20 位的數字。",
      nickname_invalid: "這個暱稱無法使用，請換一個。",
      email_invalid: "聯絡信箱的格式不對。",
      gender_invalid: "請選擇性別。",
      age_invalid: "請選擇年齡層。",
      motivation_invalid: "請寫為什麼希望加入，至少幾個字。",
      positions_invalid: "請剛好選 2 個位子。",
      playtime_invalid: "請填平日與假日的遊玩時間。",
      practice_time_invalid: "練習時間請寫具體時段，例如 20:00～22:00。",
      conduct_required: "送出前請勾選行為規範。",
      blocked_content: "內容不能包含 Discord 邀請。",
      already_pending: "這個 UID 已有一筆待審申請。",
      rate_limited: "送出太多次了，請稍後再試。",
      storage_unconfigured: "申請暫時收不下來，請稍後再試。",
      storage_unavailable: "申請暫時收不下來，請稍後再試。",
      forbidden: "請從這個網站的申請頁再送一次。",
      payload_too_large: "內容太長了，請縮短後再送。",
      invalid_json: "內容讀不到，請再送一次。",
      unsupported_media: "內容格式不對，請再送一次。",
      method_not_allowed: "請用申請頁上的按鈕送出。",
    },
  },
  heroes: {
    kicker: "08 — HEROES",
    title: "英雄",
    lead: "名單來自 Garena 傳說對決公開英雄列表。",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    source: "資料來源：Garena 傳說對決官方網站",
    all: "全部",
    open: "官方頁面",
    count: "位英雄",
    skills: "技能",
    skins: "造型",
    back: "回到英雄名單",
    unnamedSkin: "造型",
    defaultSkin: "預設",
  },
  modes: {
    kicker: "09 — MODES",
    title: "模式",
    lead: "模式名稱來自 Garena 公開頁。是否正在開放，以遊戲內為準。",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    source: "每張卡片連到原始公告。",
    players: "人數",
    rankedNote: "戰績裡標成排位賽的對局，記分板上要有排位積分變化。經典競技、競賽模式、冠軍賽是地圖名稱，沒有積分變化時照原名顯示。連結前往官方 5V5 公告。",
    detail: "模式說明",
  },
  skins: {
    kicker: "08 — SKINS",
    title: "造型",
    lead: "造型圖來自 Garena 英雄頁。官方頁沒印出造型名稱時，只顯示英雄與圖片。",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    source: "資料來源：Garena 傳說對決官方英雄頁",
    unnamed: "造型",
    original: "原皮",
    hero: "所屬英雄",
  },
  items: {
    kicker: "08 — ITEMS",
    title: "裝備",
    lead: "名稱、圖示與說明來自 Garena 公開裝備列表。常用出裝由已公開對局整理。",
    emptyTitle: "目錄暫時讀不到",
    emptyBody: "請稍後再看。",
    source: "資料來源：Garena 傳說對決官方裝備頁",
    all: "全部",
    count: "件裝備",
    builds: "常用出裝",
    buildsEmpty: "還沒有可以整理的出裝。",
    missing: "這件裝備不在目錄裡。",
  },
};

const en = {
  meta: {
    homeTitle: "MOS — Arena of Valor guild",
    homeDescription: "Guild 暮霞｜MOS (MOOHSIA). Apply only on this site. Contact Info@moohsia.com.",
    titleSuffix: "暮霞｜MOS",
  },
  nav: {
    home: "Home",
    about: "Guild",
    teams: "Teams",
    roster: "Roster",
    heroSkills: "Hero skills",
    userSkills: "Player skills",
    ultimates: "Arcana",
    news: "News",
    contact: "Contact",
    player: "Player",
    heroes: "Heroes",
    skins: "Skins",
    items: "Items",
    modes: "Modes",
    activities: "Events",
    apply: "Apply",
    menu: "Menu",
    close: "Close",
    lang: "切換為繁體中文",
    langShort: "中",
    skip: "Skip to content",
    recruitChip: "Apply on site",
    sys: "CH // PUBLIC",
    footerLabel: "Footer",
  },
  search: {
    label: "Search",
    placeholder: "Heroes, skills, arcana, items",
    empty: "No matches",
    hero: "Hero",
    skin: "Skin",
    item: "Item",
    skill: "Hero skill",
    userSkill: "Player skill",
    arcana: "Arcana",
    page: "Page",
  },
  intro: {
    label: "暮霞｜MOS",
    sub: "ARENA OF VALOR",
    skip: "Skip intro",
  },
  footer: {
    blurb: "Guild 暮霞｜MOS (MOOHSIA).",
    rule: "Apply only on this website. Discord is not open to join.",
    recruit: "Apply on site",
    explore: "On this site",
  },
  home: {
    kicker: "ARENA OF VALOR",
    kickerZh: "暮霞｜MOS",
    tagline: "Dusk holds. The line stays.",
    taglineAlt: "暮色未歇，戰線仍在。",
    lead: "Guild 暮霞｜MOS (MOOHSIA). Dusk holds. The line stays. Apply on this site. Discord is not open to join.",
    ctaTeam: "Enter the guild",
    ctaRoster: "Roster",
    ctaContact: "Email",
    ctaApply: "Apply",
    chips: [
      { text: "Arena of Valor", tone: "calm" },
      { text: "Apply on site", tone: "alert" },
      { text: "Record unannounced", tone: "calm" },
      { text: "Roster pending", tone: "calm" },
    ],
    crestSig: "SIG // DUSK",
    crestRec: "APPLY // SITE",
    hudChannel: "CH // PUBLIC",
    hudGame: "AOV // ARENA OF VALOR",
    ticker: "GUILD 暮霞｜MOS · MOOHSIA · ARENA OF VALOR · APPLY ON SITE · DISCORD IS CLOSED · ROSTER PENDING · Info@moohsia.com · ",
    metricsKicker: "00 — STAGE",
    metrics: [
      { index: "01", label: "Title", value: "Arena of Valor", note: "Home game" },
      { index: "02", label: "Gate", value: "Apply", note: "Discord is closed" },
      { index: "03", label: "Lineup", value: "Soon", note: "Roster coming soon" },
      { index: "04", label: "Mail", value: "Guild inbox", note: "Info@moohsia.com" },
    ],
    identityKicker: "01 — IDENTITY",
    identityTitle: "About MOS",
    identityLead: "Named for dusk. Playing Arena of Valor.",
    cards: [
      {
        index: "01",
        title: "The guild",
        body: "Guild 暮霞｜MOS (MOOHSIA) plays Arena of Valor. Competitive teams are listed separately.",
      },
      {
        index: "02",
        title: "Dusk",
        body: "Ember, violet, and dusk are the colors of this guild.",
      },
      {
        index: "03",
        title: "Recruitment",
        body: "Join by applying on this website. Discord is not open to join.",
      },
      {
        index: "04",
        title: "Record",
        body: "This season’s results are not out yet.",
      },
    ],
    boardKicker: "02 — STATUS",
    boardTitle: "Right now",
    boardNote: "",
    rows: [
      ["Title", "Arena of Valor"],
      ["Recruitment", "Apply on site"],
      ["Discord", "Not open to join"],
      ["Roster", "Coming soon"],
      ["Match record", "Not published"],
      ["Sponsors", "Not published"],
      ["Contact", "Info@moohsia.com"],
    ],
    fixtureKicker: "03 — FIXTURE",
    fixtureTitle: "Next match",
    fixtureLead: "The schedule is not out yet.",
    fixtureNote: "",
    fixtures: [
      { id: "NEXT", title: "To be announced", meta: "Opponent and time TBA" },
    ],
    rosterKicker: "04 — ROSTER",
    rosterTitle: "Roster",
    rosterLead: "The lineup is coming soon.",
    rosterCta: "View roster",
    signalKicker: "05 — SIGNAL",
    signalTitle: "Guild signal",
    signalCta: "Open the feed",
    finaleKicker: "06 — TRANSMIT",
    finaleTitle: "Reach the guild",
    finaleBody: "Press, partners, and guild business: write to this address. Apply on this site to join.",
    playerKicker: "07 — PLAYER",
    playerTitle: "Player record",
    playerLead: "Only published personal data is shown.",
    playerCta: "Open the player page",
    playerEmpty: "Personal record not published.",
    catalogKicker: "08 — CATALOG",
    catalogTitle: "Heroes and modes",
    catalogLead: "Official public catalog. Not a guild record.",
    heroesCta: "Hero roster",
    modesCta: "Game modes",
  },
  about: {
    kicker: "02 — GUILD",
    title: "Guild",
    lead: "Guild 暮霞｜MOS (MOOHSIA). Dusk holds. The line stays.",
    pending: "To be announced",
    manifestoKicker: "DUSK",
    manifestoTitle: "Dusk holds",
    manifesto: "The name is the last light of dusk, while the embers are still bright. This guild plays Arena of Valor.",
    principlesKicker: "NOW",
    principlesTitle: "Right now",
    principles: [
      "The game is Arena of Valor.",
      "Apply only on this website. Discord is not open to join.",
      "The roster is coming soon.",
      "This season’s results are not out yet.",
      "Sponsors are not announced.",
      "Contact Info@moohsia.com.",
    ],
    recruitTitle: "Apply on site",
    recruitBody: "To join, use the form on this website. Discord is not open to join. A one-time invite is emailed only after approval.",
  },
  roster: {
    kicker: "03 — ROSTER",
    title: "Roster",
    lead: "The roster is coming soon.",
    slot: "Roster coming soon",
    slotMeta: "Role to be announced",
    stamp: "Pending",
    stampLive: "Active",
    emptyNote: "Lineup coming soon.",
    liveLead: "The lineup.",
    rolePending: "Role unannounced",
    stageKicker: "LINEUP // PENDING",
    columns: { name: "Member", role: "Role", team: "Team" },
  },
  teams: {
    kicker: "03 — TEAMS",
    title: "Teams",
    lead: "Competitive teams in the 暮霞｜MOS guild.",
    emptyTitle: "No teams published",
    emptyBody: "Teams will be listed here once they are public.",
    open: "Open team",
    aka: "Also",
    requirements: "Requirements",
    members: "Members",
    membersEmpty: "No published members on this team yet.",
    apply: "Apply",
    applyNote: "Join the guild from the apply page. Team rules are below. Placement happens after approval.",
    missing: "That team is not listed.",
  },
  skills: {
    kicker: "08 — SKILLS",
    title: "Hero skills",
    lead: "Passives and skills for every hero, from public Garena hero pages. These are hero skills, not arcana.",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    noMatch: "No hero skills match this filter.",
    source: "Source: official Garena Arena of Valor hero pages.",
    method: "A four-skill page is passive, skill 1, skill 2, then skill 3. Tokens like {0} are official placeholders. This site does not fill in cooldown or damage.",
    unresolved: "These heroes do not have four skills, so they stay in the published order without guessing which one is the passive:",
    search: "Search heroes or skills",
    all: "All",
    count: "heroes",
  },
  userSkills: {
    kicker: "09 — USER",
    title: "Player skills",
    lead: "Skills the player brings into a match, such as teleport. Not hero abilities. Garena's public page calls them challenger skills.",
    official: "Challenger skills",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    source: "Source: the public Garena Arena of Valor page.",
    count: "skills",
  },
  ultimates: {
    kicker: "10 — ARCANA",
    title: "Arcana",
    lead: "The pre-match glyph loadout. Garena's public page calls this the arcana list, in three levels. It is not a hero's fourth skill.",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    noMatch: "No arcana match this filter.",
    source: "Source: the public Garena arcana list.",
    method: "Names, levels, tags, and effects are copied from the public arcana list. This site does not change the numbers.",
    search: "Search arcana",
    levelAll: "All levels",
    tagAll: "All tags",
    levels: { 1: "Level 1", 2: "Level 2", 3: "Level 3" },
    count: "arcana",
    listLink: "Arcana list",
    glyphsTitle: "Glyph factions",
    glyphsLead: "Garena also announced a separate glyph system. The public game pages do not list each glyph or its numbers, so only the four factions are shown.",
    glyphsPendingStamp: "Unlisted",
    glyphsPending: "The public pages do not list the individual glyphs in this faction.",
    glyphsSource: "Glyph system announcement",
  },
  news: {
    kicker: "04 — SIGNAL",
    title: "News",
    lead: "Matches and guild news.",
    emptyTitle: "No news yet",
    emptyBody: "New posts will show up here.",
    silent: "SIGNAL // SILENT",
    feed: "NO PUBLIC FEED",
    wireLabel: "Wire",
    reserved: [
      { id: "01", title: "No announcement", meta: "—" },
      { id: "02", title: "No fixture", meta: "—" },
      { id: "03", title: "No result", meta: "—" },
    ],
    reservedNote: "",
  },
  contact: {
    kicker: "05 — CONTACT",
    title: "Contact",
    lead: "Press, partners, and guild business: write here.",
    emailLabel: "Email the guild",
    only: "Info@moohsia.com",
    recruitTitle: "Apply on site",
    recruitBody: "Applications are accepted only on this website. Discord is not open to join.",
    sheetKicker: "CHANNELS",
    sheet: [
      ["01  Mail", "Info@moohsia.com", "Open"],
      ["02  Recruit", "Apply on site", "Open"],
      ["03  Discord", "Not open to join", "Shut"],
    ],
    writeTitle: "Guild inbox",
    writeBody: "Write to Info@moohsia.com. Apply on this site to join.",
  },
  notFound: {
    kicker: "404 — OFF MAP",
    title: "Page not on the map",
    lead: "That address is not part of the guild site.",
    back: "Back home",
  },
  player: {
    kicker: "07 — PLAYER",
    title: "Player profile",
    lead: "Personal stats appear only after they are published.",
    emptyTitle: "Not published",
    emptyBody: "The personal record is not public yet. It shows up here after it is filled in and published.",
    pending: "To be announced",
    handleLabel: "Game ID",
    nameLabel: "Display name",
    roleLabel: "Role",
    laneLabel: "Lane",
    rankLabel: "Rank",
    peakLabel: "Peak",
    joinLabel: "Joined",
    seasonLabel: "Season",
    serverLabel: "Server",
    titleLabel: "Title",
    heroesLabel: "Signature heroes",
    bioLabel: "Bio",
    statsKicker: "RECORD",
    matchesKicker: "MATCHES",
    matchesEmpty: "No published matches.",
    played: "Played",
    wins: "Wins",
    winRate: "Win rate",
    kda: "KDA",
    kills: "Kills",
    deaths: "Deaths",
    assists: "Assists",
    gold: "Gold",
    damage: "Damage",
    mvp: "MVP",
    minions: "Last hits",
    lastHits: "Last hits",
    jungle: "Jungle gold",
    goldTotal: "Gold",
    healing: "Healing",
    tower: "Tower damage",
    control: "CC",
    damageRatio: "Damage ratio",
    takenPer: "Taken per death",
    takenLabel: "Damage taken",
    heroDamage: "Hero damage",
    teamfight: "Teamfight",
    rankDelta: "Rank pts",
    power: "Legend power",
    score: "Score",
    uidLabel: "UID",
    sections: {
      heroes: "Heroes",
      history: "History",
      analysis: "Analysis",
      battle: "Battle",
      builds: "Builds",
      reputation: "Reputation",
      honors: "Championship honors",
      titles: "Honor titles",
      bonds: "Bonds",
    },
    radar: { output: "Damage", kda: "KDA", farm: "Farm", teamfight: "Teamfight", survival: "Survival" },
    medals: {
      godlike: "Godlike",
      penta: "Penta",
      quadra: "Quadra",
      triple: "Triple",
      supreme: "Supreme",
      gold: "Gold",
      silver: "Silver",
      loseMvp: "Loss MVP",
    },
    tabs: {
      board: "Overview",
      data: "Stats",
      output: "Damage",
      survival: "Taken",
      farm: "Farm",
      record: "Score",
      team: "Team",
    },
    charts: "Charts",
    analysis: {
      title: "Analysis",
      lead: "Counted only from published matches.",
      empty: "Not enough data",
      recent: "Recent win rate",
      last10: "Last 10",
      last20: "Last 20",
      overall: "Overall",
      record: "{wins}W · {losses}L",
      games: "{n} games",
      heroes: "Hero win rate",
      trend: "KDA / damage",
      trendNote: "Left to right is older to newer.",
      when: "When",
      kda: "KDA",
      damage: "Damage",
      compare: "Wins vs losses",
      winWord: "Win",
      lossWord: "Loss",
      gold: "Gold",
      average: "avg",
      modes: "Modes",
      modesNote: "Grouped by mode, with the map when one is stored.",
      myriad: "k",
    },
    highlight: "Highlight",
    noChart: "No numbers to chart yet.",
    reputationEmpty: "Reputation has not been entered.",
    honorsEmpty: "No championship honors yet.",
    titlesEmpty: "No honor titles yet.",
    heroesEmpty: "No signature heroes yet.",
    buildsEmpty: "No item sets yet.",
    buildsTitle: "Common builds",
    skinsTitle: "Skins",
    skinsEmpty: "No skins recorded.",
    heroTable: "Hero details",
    classic: "Classic",
    magic: "Magic chess",
    magicEmpty: "No matches yet.",
    bondsEmpty: "No bonds recorded.",
    derivedNote: "Games and win rate are counted from published matches. Radar and medals appear after a season is filled in.",
    columns: { hero: "Hero", result: "Result", points: "Points", items: "Items", mode: "Mode" },
    openDetail: "Open match",
    skillOrder: "Skill order",
    items: "Items",
    boots: "Boots",
    enchant: "Enchant",
    arcana: "Arcana",
    skin: "Skin",
    map: "Map",
  },
  activities: {
    kicker: "10 — OFFICIAL",
    title: "Official events",
    lead: "Activities, news, and esports posts from public Garena pages. Not this guild's fixtures.",
    emptyTitle: "No events loaded",
    emptyBody: "The daily refresh, or the admin refresh, fills this list from the public pages.",
    source: "Source: public Garena Arena of Valor news pages. What is still live is whatever those pages say.",
    all: "All",
    activity: "Event",
    announcement: "News",
    esports: "Esports",
    open: "Official post",
  },
  apply: {
    kicker: "11 — APPLY",
    title: "Apply",
    lead: "Guild 暮霞｜MOS (MOOHSIA) takes applications only on this website. Discord is not open to join.",
    teamNote: "This form joins the guild. Each team's requirements are on its team page, including MOOHSIA.",
    rank: "Highest ranked tier",
    rankHint: "Gold is the minimum. Below Gold is rejected.",
    uid: "UID",
    uidHint: "Digits only.",
    nickname: "In-game name",
    email: "Email",
    gender: "Gender",
    age: "Age band",
    motivation: "Why do you want to join?",
    positions: "Roles",
    positionsHint: "Choose exactly 2.",
    weekday: "Weekday play time",
    holiday: "Weekend play time",
    practice: "Practice time you can make",
    practiceHint: "Use a concrete range, for example 20:00～22:00.",
    conduct: "I agree: respect, kindness, and inclusion; no money between members; follow the official rules.",
    submit: "Submit application",
    discord: "Discord is not open for cold join. After approval, the owner emails a one-time invite.",
    sent: "Application received.",
    sentBody: "When mail is configured, the owner sees it at Info@moohsia.com.",
    mailDelayed: "Your application is saved. The notification email may be delayed, and this submission still counts.",
    fail: "This was not submitted.",
    errors: {
      rank_below_gold: "Highest tier must be Gold or above.",
      uid_invalid: "UID must be 4 to 20 digits.",
      nickname_invalid: "That name cannot be used. Please choose another.",
      email_invalid: "That email address is not valid.",
      gender_invalid: "Choose a gender option.",
      age_invalid: "Choose an age band.",
      motivation_invalid: "Say why you want to join, in a few words at least.",
      positions_invalid: "Choose exactly 2 roles.",
      playtime_invalid: "Enter both weekday and weekend play times.",
      practice_time_invalid: "Practice time needs a clock range, for example 20:00～22:00.",
      conduct_required: "Check the conduct agreement before submitting.",
      blocked_content: "Do not include a Discord invite.",
      already_pending: "This UID already has an application waiting for review.",
      rate_limited: "Too many attempts. Please wait and try again.",
      storage_unconfigured: "Applications cannot be saved right now. Please try again later.",
      storage_unavailable: "Applications cannot be saved right now. Please try again later.",
      forbidden: "Submit again from this site's apply page.",
      payload_too_large: "That is too long. Shorten it and try again.",
      invalid_json: "The form could not be read. Please try again.",
      unsupported_media: "The form format was not accepted. Please try again.",
      method_not_allowed: "Use the button on the apply page.",
    },
  },
  heroes: {
    kicker: "08 — HEROES",
    title: "Heroes",
    lead: "The list comes from the public Garena Arena of Valor hero page.",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    source: "Source: the official Garena Arena of Valor site",
    all: "All",
    open: "Official page",
    count: "heroes",
    skills: "Skills",
    skins: "Skins",
    back: "Back to heroes",
    unnamedSkin: "Skin",
    defaultSkin: "Default",
  },
  modes: {
    kicker: "09 — MODES",
    title: "Modes",
    lead: "Mode names come from public Garena pages. What is in rotation is whatever the game shows.",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    source: "Each card links to the original post.",
    players: "Players",
    rankedNote: "A history row is ranked only when its scoreboard includes a rank-point change. 經典競技, 競賽模式, and 冠軍賽 are map names and stay as written when that change is missing. The link opens the official 5V5 post.",
    detail: "Mode notes",
  },
  skins: {
    kicker: "08 — SKINS",
    title: "Skins",
    lead: "Skin art comes from Garena hero pages. When the page does not print a skin name, only the hero and image are shown.",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    source: "Source: official Garena hero pages",
    unnamed: "Skin",
    original: "Default",
    hero: "Hero",
  },
  items: {
    kicker: "08 — ITEMS",
    title: "Items",
    lead: "Names, icons, and descriptions come from the public Garena item list. Common builds are counted from published matches.",
    emptyTitle: "Catalog unavailable",
    emptyBody: "Try again in a moment.",
    source: "Source: the official Garena item page",
    all: "All",
    count: "items",
    builds: "Common builds",
    buildsEmpty: "No item sets yet.",
    missing: "That item is not in the catalog.",
  },
};

function snapshot() {
  return {
    version: 1,
    contactEmail: CONTACT_EMAIL,
    placeholderSlots: PLACEHOLDER_SLOTS,
    profileFields: structuredClone(profileFields),
    teams: structuredClone(teams),
    rosterMembers: structuredClone(rosterMembers),
    newsPosts: structuredClone(newsPosts),
    player: emptyPlayer(),
    copy: {
      zh: structuredClone(zh),
      en: structuredClone(en),
    },
  };
}

let current = snapshot();

export function getDefaultDocument() {
  return snapshot();
}

function mergeCopy(base, incoming) {
  if (typeof base === "string") return typeof incoming === "string" ? incoming : base;
  if (Array.isArray(base)) return Array.isArray(incoming) ? incoming : base;
  if (base && typeof base === "object") {
    const out = {};
    for (const key of Object.keys(base)) out[key] = mergeCopy(base[key], incoming?.[key]);
    return out;
  }
  return base;
}

function adoptPublicPlayer(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const matches = Array.isArray(value.matches) ? value.matches.map((match) => ({ ...match, publish: true })) : [];
  return toPublicPlayer(cleanPlayer({ ...value, publish: true, matches }));
}

function usableEmail(value, fallback) {
  const text = typeof value === "string" ? value.trim() : "";
  if (/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(text) && text.length <= 120) return text;
  return fallback;
}

/**
 * Overlay published CMS content onto the built-in defaults.
 * Missing pieces stay on the defaults so a partial document cannot blank the site.
 * @param {unknown} payload
 */
export function applyPublishedContent(payload) {
  const base = snapshot();
  const doc = payload && typeof payload === "object" ? /** @type {Record<string, any>} */ (payload) : {};
  const slots = Number(doc.placeholderSlots);
  current = {
    version: 1,
    contactEmail: usableEmail(doc.contactEmail, base.contactEmail),
    placeholderSlots: Number.isInteger(slots) && slots >= 0 && slots <= 12 ? slots : base.placeholderSlots,
    profileFields: Array.isArray(doc.profileFields) ? doc.profileFields : base.profileFields,
    teams: Array.isArray(doc.teams) ? doc.teams : base.teams,
    rosterMembers: Array.isArray(doc.rosterMembers) ? doc.rosterMembers.map((member) => ({ ...member, team: memberTeamSlug(member) })) : base.rosterMembers,
    newsPosts: Array.isArray(doc.newsPosts) ? doc.newsPosts : base.newsPosts,
    player: adoptPublicPlayer(doc.player),
    copy: {
      zh: mergeCopy(base.copy.zh, doc.copy?.zh),
      en: mergeCopy(base.copy.en, doc.copy?.en),
    },
  };
}

export function getCopy(lang) {
  return lang === "en" ? current.copy.en : current.copy.zh;
}

export function getRosterMembers() {
  return current.rosterMembers;
}

export function getTeams() {
  return current.teams;
}

export function getNewsPosts() {
  return current.newsPosts;
}

export function getProfileFields() {
  return current.profileFields;
}

export function getPlaceholderSlots() {
  return current.placeholderSlots;
}

export function getContactEmail() {
  return current.contactEmail;
}

export function getPlayer() {
  const player = current.player;
  if (!player || player.publish === false) return null;
  return player;
}

export function getMailto() {
  return `mailto:${current.contactEmail}`;
}

export const NAV = [
  { href: "/", key: "home" },
  { href: "/about", key: "about" },
  { href: "/teams", key: "teams" },
  { href: "/roster", key: "roster" },
  { href: "/heroes", key: "heroes" },
  { href: "/skills", key: "heroSkills", code: "SKILLS" },
  { href: "/user-skills", key: "userSkills", code: "USER" },
  { href: "/ultimates", key: "ultimates", code: "ARCANA" },
  { href: "/skins", key: "skins" },
  { href: "/items", key: "items" },
  { href: "/modes", key: "modes" },
  { href: "/activities", key: "activities" },
  { href: "/news", key: "news" },
  { href: "/apply", key: "apply" },
  { href: "/contact", key: "contact" },
];
