/**
 * Editable team facts.
 * Leave strings blank until they are confirmed. Do not invent championships,
 * player names, sponsors, or a Discord invite.
 */

export const PLACEHOLDER_SLOTS = 5;

/** @type {{ id: string, name: { zh: string, en: string }, role: { zh: string, en: string } }[]} */
export const rosterMembers = [];

/** @type {{ id: string, date: string, title: { zh: string, en: string }, body: { zh: string, en: string } }[]} */
export const newsPosts = [];

export const profileFields = [
  { id: "founded", zh: "成立", en: "Founded", value: { zh: "", en: "" } },
  { id: "base", zh: "基地", en: "Base", value: { zh: "", en: "" } },
  { id: "season", zh: "目前賽季", en: "Season", value: { zh: "", en: "" } },
  { id: "record", zh: "公開戰績", en: "Public record", value: { zh: "", en: "" } },
  { id: "sponsors", zh: "贊助", en: "Sponsors", value: { zh: "", en: "" } },
];

const zh = {
  meta: {
    homeTitle: "暮霞｜MOS — 傳說對決戰隊",
    homeDescription: "暮霞｜MOS 是傳說對決戰隊的公開網站。招募不開放。聯絡 Info@moohsia.com。",
    titleSuffix: "暮霞｜MOS",
  },
  nav: {
    home: "首頁",
    about: "戰隊",
    roster: "成員",
    news: "動態",
    contact: "聯絡",
    verify: "驗證",
    menu: "選單",
    close: "關閉",
    lang: "切換為 English",
    langShort: "EN",
    skip: "跳至內容",
    recruitChip: "招募：不開放",
    sys: "SYS ONLINE",
  },
  footer: {
    blurb: "傳說對決戰隊的公開網站。這裡只呈現戰隊資訊。",
    rule: "公開資訊以本站頁面為準。",
    recruit: "不開放招募",
  },
  home: {
    kicker: "ARENA OF VALOR",
    kickerZh: "傳說對決戰隊",
    tagline: "暮色未歇，戰線仍在。",
    taglineAlt: "Dusk holds. The line stays.",
    lead: "暮霞｜MOS 是傳說對決戰隊。這個網站只公開戰隊本身的資訊：身份、成員、動態，以及唯一的聯絡方式。",
    ctaTeam: "認識戰隊",
    ctaVerify: "驗證通道",
    chips: [
      { text: "傳說對決", tone: "calm" },
      { text: "招募：不開放", tone: "alert" },
      { text: "戰績：尚未公開", tone: "calm" },
    ],
    crestSig: "SIG // DUSK",
    crestRec: "REC // CLOSED",
    identityKicker: "01 — IDENTITY",
    identityTitle: "戰隊識別",
    cards: [
      {
        index: "01",
        title: "戰隊身份",
        body: "暮霞｜MOS（MOS / Moohsia）是一支以傳說對決為主場的戰隊。公開頁面不放個人品牌敘事。",
      },
      {
        index: "02",
        title: "招募狀態",
        body: "不開放招募。目前不受理公開加入或試訓申請，網站上也沒有報名表。",
      },
      {
        index: "03",
        title: "內部通道",
        body: "內部 Discord 需要先通過驗證。邀請連結不會公開張貼；未設定時顯示即將開放。",
      },
    ],
    boardKicker: "02 — STATUS",
    boardTitle: "公開狀態",
    boardNote: "空白代表尚未確認，不是零戰績，也不是隱藏成績。",
    rows: [
      ["遊戲", "傳說對決"],
      ["公開招募", "不開放"],
      ["試訓申請", "不受理"],
      ["成員名單", "即將公開"],
      ["賽事成績", "尚未公布"],
      ["贊助", "尚未公開"],
      ["內部 Discord", "通過驗證後加入"],
      ["聯絡", "Info@moohsia.com"],
    ],
    pathKicker: "03 — CHANNELS",
    pathTitle: "對外只留兩條路",
    emailTitle: "戰隊信箱",
    emailBody: "公開聯絡只有這個信箱。沒有其他郵件、電話或私人帳號。",
    discordTitle: "內部 Discord",
    discordBody: "通過驗證後加入內部 Discord。這不是公開群組連結。",
    discordCta: "了解驗證",
  },
  about: {
    kicker: "02 — TEAM",
    title: "戰隊",
    lead: "以下欄位會在資料確認後更新。沒有填上的項目維持待公布，不會用推測的成績、贊助或歷史補上。",
    pending: "待公布",
    principlesKicker: "PUBLIC RULES",
    principlesTitle: "本站公開原則",
    principles: [
      "只發布已確認的戰隊資訊。",
      "不開放招募，不受理試訓申請。",
      "不列出尚未公開的成員名稱。",
      "不宣稱尚未公布的賽事成績。",
      "不宣稱與 Garena 的官方合作，也不做官方對戰資料同步。",
      "聯絡方式只有 Info@moohsia.com。",
    ],
    recruitTitle: "不開放招募",
    recruitBody: "目前沒有公開試訓，也沒有加入申請表。請勿來信詢問報名。",
  },
  roster: {
    kicker: "03 — ROSTER",
    title: "成員",
    lead: "正式名單確認前，不顯示玩家名稱或位置。",
    slot: "成員資訊即將公開",
    slotMeta: "位置與選手名稱尚未公開",
    emptyNote: "名額只是版面預留，不代表已有五位公開選手。",
    rolePending: "位置未公開",
  },
  news: {
    kicker: "04 — SIGNAL",
    title: "動態",
    lead: "賽事公告與戰隊消息確認後，會列在這裡。",
    emptyTitle: "目前沒有公開動態",
    emptyBody: "沒有比數、沒有賽程轉播、也沒有假的即時戰績。確認過的消息才會出現。",
    silent: "SIGNAL // SILENT",
  },
  contact: {
    kicker: "05 — CONTACT",
    title: "聯絡",
    lead: "戰隊的公開聯絡方式只有下方信箱。",
    emailLabel: "寫信給戰隊",
    only: "沒有第二個信箱，沒有電話。",
    discordTitle: "內部 Discord",
    discordBody: "通過驗證後加入內部 Discord。請先完成驗證申請，不要在信件裡索取公開邀請。",
    discordCta: "前往驗證",
    comingSoon: "邀請連結尚未設定，即將開放。",
    staged: "邀請已備妥。通過驗證前，這個網站不會顯示連結。",
    recruitTitle: "不開放招募",
    recruitBody: "來信若是試訓或加入申請，戰隊不會受理。",
  },
  verify: {
    kicker: "06 — ACCESS",
    title: "驗證",
    lead: "內部 Discord 只給通過驗證的人。既有成員或受邀者可以送出申請，由戰隊人工審核。",
    banner: "招募：不開放。此頁不是試訓，也不是公開加入申請。",
    steps: [
      { title: "識別", body: "填寫傳說對決 ID 與 Discord 使用者名稱。" },
      { title: "送出", body: "建立一筆站內申請存根與編號。" },
      { title: "審核", body: "戰隊人工確認。不會連線 Garena 官方 API。" },
      { title: "解鎖", body: "通過之後才會開放內部 Discord 入口。" },
    ],
    formTitle: "驗證申請",
    aovLabel: "傳說對決 ID",
    aovHint: "2–24 字。不要填信箱或連結。",
    discordLabel: "Discord 使用者名稱",
    discordHint: "使用者名稱即可，不要貼上邀請連結。",
    ack: "我了解這只是站內驗證存根：不會同步 Garena 官方資料，也不會立即開通 Discord。",
    submit: "送出驗證申請",
    sending: "送出中",
    honeypot: "網站",
    gateTitle: "內部 Discord",
    gateCta: "通過驗證後加入內部 Discord",
    comingSoon: "邀請連結尚未設定，即將開放。",
    staged: "邀請已備妥。通過驗證前不會顯示連結。",
    gateNote: "此按鈕保持鎖定。公開頁面沒有邀請網址。",
    human: "若需改以信件聯繫戰隊，只使用",
    errors: {
      invalid_aov_id: "請填寫有效的傳說對決 ID。",
      invalid_discord: "請填寫 Discord 使用者名稱，不要貼連結或信箱。",
      ack_required: "請先勾選說明，確認你了解這不是官方同步。",
      invalid_json: "資料格式不正確，請再送一次。",
      payload_too_large: "內容過長。",
      network: "現在無法送出。請稍後再試，或寫信到戰隊信箱。",
      server_error: "服務暫時無法處理申請。",
    },
    receiptTitle: "申請已建立",
    receiptBody: "這是本地存根。伺服器不保存這筆申請，也不代表已經通過審核。",
    labels: {
      id: "申請編號",
      status: "狀態",
      pending: "等待人工審核",
      discord: "Discord 入口",
      locked: "未解鎖",
      garena: "Garena 官方同步",
      unsynced: "未同步",
      store: "保存位置",
      local: "僅此瀏覽器",
      aov: "傳說對決 ID",
      handle: "Discord 名稱",
    },
    clear: "清除這台裝置上的申請紀錄",
    again: "再送出會覆蓋這台裝置上的上一筆本地紀錄。",
  },
  notFound: {
    kicker: "404 — OFF MAP",
    title: "找不到這個頁面",
    lead: "這個網址不在戰隊站內。",
    back: "回到首頁",
  },
};

const en = {
  meta: {
    homeTitle: "MOS — Arena of Valor team",
    homeDescription: "暮霞｜MOS is an Arena of Valor team site. Recruitment is closed. Contact Info@moohsia.com.",
    titleSuffix: "暮霞｜MOS",
  },
  nav: {
    home: "Home",
    about: "Team",
    roster: "Roster",
    news: "News",
    contact: "Contact",
    verify: "Verify",
    menu: "Menu",
    close: "Close",
    lang: "切換為繁體中文",
    langShort: "中",
    skip: "Skip to content",
    recruitChip: "Recruitment closed",
    sys: "SYS ONLINE",
  },
  footer: {
    blurb: "Public site for the Arena of Valor team. Team information only.",
    rule: "What is published on this site is the public record.",
    recruit: "Recruitment closed",
  },
  home: {
    kicker: "ARENA OF VALOR",
    kickerZh: "暮霞｜MOS",
    tagline: "Dusk holds. The line stays.",
    taglineAlt: "暮色未歇，戰線仍在。",
    lead: "暮霞｜MOS is an Arena of Valor team. This site publishes the team itself: identity, roster, news, and one contact address.",
    ctaTeam: "The team",
    ctaVerify: "Verification",
    chips: [
      { text: "Arena of Valor", tone: "calm" },
      { text: "Recruitment closed", tone: "alert" },
      { text: "Record unannounced", tone: "calm" },
    ],
    crestSig: "SIG // DUSK",
    crestRec: "REC // CLOSED",
    identityKicker: "01 — IDENTITY",
    identityTitle: "Team identity",
    cards: [
      {
        index: "01",
        title: "Who this is",
        body: "暮霞｜MOS (MOS / Moohsia) is an Arena of Valor team. The public site is not a personal brand.",
      },
      {
        index: "02",
        title: "Recruitment",
        body: "Recruitment is closed. There is no open tryout and no application form.",
      },
      {
        index: "03",
        title: "Internal channel",
        body: "The internal Discord opens after verification. No public invite is posted. If unset, it stays coming soon.",
      },
    ],
    boardKicker: "02 — STATUS",
    boardTitle: "Public status",
    boardNote: "A blank field means unconfirmed. It is not a hidden record and not a claimed result.",
    rows: [
      ["Title", "Arena of Valor"],
      ["Recruitment", "Closed"],
      ["Tryouts", "Not accepted"],
      ["Roster", "Coming soon"],
      ["Match record", "Not published"],
      ["Sponsors", "Not published"],
      ["Internal Discord", "After verification"],
      ["Contact", "Info@moohsia.com"],
    ],
    pathKicker: "03 — CHANNELS",
    pathTitle: "Two public paths",
    emailTitle: "Team inbox",
    emailBody: "This is the only public address. No other email or phone number.",
    discordTitle: "Internal Discord",
    discordBody: "Join the internal Discord after verification. This is not a public invite.",
    discordCta: "How verification works",
  },
  about: {
    kicker: "02 — TEAM",
    title: "Team",
    lead: "These fields update when the facts are confirmed. Empty rows stay unpublished. Nothing here is guessed.",
    pending: "To be announced",
    principlesKicker: "PUBLIC RULES",
    principlesTitle: "What this site will not claim",
    principles: [
      "Only confirmed team information is published.",
      "Recruitment is closed. Tryout requests are not accepted.",
      "Unannounced player names are not listed.",
      "Unannounced results are not claimed.",
      "No Garena partnership and no official match sync.",
      "The only contact is Info@moohsia.com.",
    ],
    recruitTitle: "Recruitment is closed",
    recruitBody: "There is no public tryout and no join form. Please do not email to apply.",
  },
  roster: {
    kicker: "03 — ROSTER",
    title: "Roster",
    lead: "Player names and roles stay hidden until the roster is confirmed.",
    slot: "Roster details coming soon",
    slotMeta: "Name and role not published",
    emptyNote: "These slots are layout only. They are not five announced players.",
    rolePending: "Role unannounced",
  },
  news: {
    kicker: "04 — SIGNAL",
    title: "News",
    lead: "Match notes and team updates appear here after they are confirmed.",
    emptyTitle: "No public updates",
    emptyBody: "No scores, no broadcast schedule, and no simulated live stats. Only confirmed posts will show.",
    silent: "SIGNAL // SILENT",
  },
  contact: {
    kicker: "05 — CONTACT",
    title: "Contact",
    lead: "The team has one public contact.",
    emailLabel: "Email the team",
    only: "No second address. No phone number.",
    discordTitle: "Internal Discord",
    discordBody: "Join the internal Discord after verification. Do not ask for a public invite by email.",
    discordCta: "Go to verification",
    comingSoon: "Invite link is not set yet. Coming soon.",
    staged: "An invite is staged. This site will not show the link before verification.",
    recruitTitle: "Recruitment is closed",
    recruitBody: "Emails asking for a tryout or a roster spot will not be treated as applications.",
  },
  verify: {
    kicker: "06 — ACCESS",
    title: "Verification",
    lead: "The internal Discord is for people who pass verification. Current members or invited people may submit a request for manual review.",
    banner: "Recruitment is closed. This is not a tryout and not an open application.",
    steps: [
      { title: "Identify", body: "Enter an Arena of Valor ID and a Discord username." },
      { title: "Submit", body: "The site creates a local stub and a receipt id." },
      { title: "Review", body: "The team reviews it by hand. There is no Garena API sync." },
      { title: "Unlock", body: "The internal Discord entry opens only after approval." },
    ],
    formTitle: "Verification request",
    aovLabel: "Arena of Valor ID",
    aovHint: "2–24 characters. No email address or link.",
    discordLabel: "Discord username",
    discordHint: "Username only. Do not paste an invite link.",
    ack: "I understand this is an on-site stub. It does not sync with Garena and it does not unlock Discord.",
    submit: "Submit verification request",
    sending: "Sending",
    honeypot: "Website",
    gateTitle: "Internal Discord",
    gateCta: "Join the internal Discord after verification",
    comingSoon: "Invite link is not set yet. Coming soon.",
    staged: "An invite is staged. The link stays hidden until verification passes.",
    gateNote: "This control stays locked. The public page has no invite URL.",
    human: "To reach the team another way, use only",
    errors: {
      invalid_aov_id: "Enter a valid Arena of Valor ID.",
      invalid_discord: "Enter a Discord username, not a link or email.",
      ack_required: "Confirm that you understand this is not an official sync.",
      invalid_json: "The form could not be read. Try again.",
      payload_too_large: "That was too long.",
      network: "The request could not be sent. Try again, or email the team.",
      server_error: "The service could not accept the request.",
    },
    receiptTitle: "Request created",
    receiptBody: "This stub lives in this browser. The server does not store it, and it is not an approval.",
    labels: {
      id: "Receipt",
      status: "Status",
      pending: "Pending manual review",
      discord: "Discord access",
      locked: "Locked",
      garena: "Garena sync",
      unsynced: "Not synced",
      store: "Stored",
      local: "This browser only",
      aov: "Arena of Valor ID",
      handle: "Discord name",
    },
    clear: "Remove the receipt from this device",
    again: "Sending again replaces the previous local receipt on this device.",
  },
  notFound: {
    kicker: "404 — OFF MAP",
    title: "Page not on the map",
    lead: "That address is not part of the team site.",
    back: "Back home",
  },
};

export function getCopy(lang) {
  return lang === "en" ? en : zh;
}

export const NAV = [
  { href: "/", key: "home" },
  { href: "/about", key: "about" },
  { href: "/roster", key: "roster" },
  { href: "/news", key: "news" },
  { href: "/contact", key: "contact" },
  { href: "/verify", key: "verify" },
];
